In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
df = pd.read_csv('heart_attack_prediction_dataset.csv')
df.head()

Patient ID  Age     Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  \
0    BMW7812   67    Male          208         158/88          72         0   
1    CZE1114   21    Male          389         165/93          98         1   
2    BNI9906   21  Female          324         174/99          72         1   
3    JLN3497   84    Male          383        163/100          73         1   
4    GFO8847   66    Male          318          91/88          93         1   

   Family History  Smoking  Obesity  ...  Sedentary Hours Per Day  Income  \
0               0        1        0  ...                 6.615001  261404   
1               1        1        1  ...                 4.963459  285768   
2               0        0        0  ...                 9.463426  235282   
3               1        1        0  ...                 7.648981  125640   
4               1        1        1  ...                 1.514821  160555   

         BMI  Triglycerides  Physical Activity Days Per Week  \
0  31.251233            286                                0   
1  27.194973            235                                1   
2  28.176571            587                                4   
3  36.464704            378                                3   
4  21.809144            231                                1   

   Sleep Hours Per Day    Country      Continent           Hemisphere  \
0                    6  Argentina  South America  Southern Hemisphere   
1                    7     Canada  North America  Northern Hemisphere   
2                    4     France         Europe  Northern Hemisphere   
3                    4     Canada  North America  Northern Hemisphere   
4                    5   Thailand           Asia  Northern Hemisphere   

   Heart Attack Risk  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 26 columns]

In [7]:
df[['up', 'down']] = df['Blood Pressure'].str.split('/', expand=True)

In [8]:
df.head()

Patient ID  Age     Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  \
0    BMW7812   67    Male          208         158/88          72         0   
1    CZE1114   21    Male          389         165/93          98         1   
2    BNI9906   21  Female          324         174/99          72         1   
3    JLN3497   84    Male          383        163/100          73         1   
4    GFO8847   66    Male          318          91/88          93         1   

   Family History  Smoking  Obesity  ...        BMI  Triglycerides  \
0               0        1        0  ...  31.251233            286   
1               1        1        1  ...  27.194973            235   
2               0        0        0  ...  28.176571            587   
3               1        1        0  ...  36.464704            378   
4               1        1        1  ...  21.809144            231   

  Physical Activity Days Per Week  Sleep Hours Per Day    Country  \
0                               0                    6  Argentina   
1                               1                    7     Canada   
2                               4                    4     France   
3                               3                    4     Canada   
4                               1                    5   Thailand   

       Continent           Hemisphere  Heart Attack Risk   up  down  
0  South America  Southern Hemisphere                  0  158    88  
1  North America  Northern Hemisphere                  0  165    93  
2         Europe  Northern Hemisphere                  0  174    99  
3  North America  Northern Hemisphere                  0  163   100  
4           Asia  Northern Hemisphere                  0   91    88  

[5 rows x 28 columns]

In [9]:
df.drop(columns=['Blood Pressure'], inplace=True)

In [10]:
df.head()

Patient ID  Age     Sex  Cholesterol  Heart Rate  Diabetes  Family History  \
0    BMW7812   67    Male          208          72         0               0   
1    CZE1114   21    Male          389          98         1               1   
2    BNI9906   21  Female          324          72         1               0   
3    JLN3497   84    Male          383          73         1               1   
4    GFO8847   66    Male          318          93         1               1   

   Smoking  Obesity  Alcohol Consumption  ...        BMI Triglycerides  \
0        1        0                    0  ...  31.251233           286   
1        1        1                    1  ...  27.194973           235   
2        0        0                    0  ...  28.176571           587   
3        1        0                    1  ...  36.464704           378   
4        1        1                    0  ...  21.809144           231   

   Physical Activity Days Per Week  Sleep Hours Per Day    Country  \
0                                0                    6  Argentina   
1                                1                    7     Canada   
2                                4                    4     France   
3                                3                    4     Canada   
4                                1                    5   Thailand   

       Continent           Hemisphere  Heart Attack Risk   up  down  
0  South America  Southern Hemisphere                  0  158    88  
1  North America  Northern Hemisphere                  0  165    93  
2         Europe  Northern Hemisphere                  0  174    99  
3  North America  Northern Hemisphere                  0  163   100  
4           Asia  Northern Hemisphere                  0   91    88  

[5 rows x 27 columns]

In [11]:
df = df.drop(columns=['Patient ID', 'Country', 'Continent', 'Hemisphere'])

In [12]:
df.head()

Age     Sex  Cholesterol  Heart Rate  Diabetes  Family History  Smoking  \
0   67    Male          208          72         0               0        1   
1   21    Male          389          98         1               1        1   
2   21  Female          324          72         1               0        0   
3   84    Male          383          73         1               1        1   
4   66    Male          318          93         1               1        1   

   Obesity  Alcohol Consumption  Exercise Hours Per Week  ... Stress Level  \
0        0                    0                 4.168189  ...            9   
1        1                    1                 1.813242  ...            1   
2        0                    0                 2.078353  ...            9   
3        0                    1                 9.828130  ...            9   
4        1                    0                 5.804299  ...            6   

   Sedentary Hours Per Day  Income        BMI  Triglycerides  \
0                 6.615001  261404  31.251233            286   
1                 4.963459  285768  27.194973            235   
2                 9.463426  235282  28.176571            587   
3                 7.648981  125640  36.464704            378   
4                 1.514821  160555  21.809144            231   

   Physical Activity Days Per Week  Sleep Hours Per Day  Heart Attack Risk  \
0                                0                    6                  0   
1                                1                    7                  0   
2                                4                    4                  0   
3                                3                    4                  0   
4                                1                    5                  0   

    up  down  
0  158    88  
1  165    93  
2  174    99  
3  163   100  
4   91    88  

[5 rows x 23 columns]

In [13]:
df.isnull().sum()

Age                                0
Sex                                0
Cholesterol                        0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Heart Attack Risk                  0
up                                 0
down                               0
dtype: int64

In [14]:
df['up'] = df['up'].astype(float)
df['down'] = df['down'].astype(float)

In [15]:
X = df.drop(columns=['Heart Attack Risk'])
y = df['Heart Attack Risk']

In [16]:
y.value_counts()

Heart Attack Risk
0    5624
1    3139
Name: count, dtype: int64

In [17]:
y.isnull().sum()

np.int64(0)

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [19]:
ohe_columns = [columns for columns in X.columns if X[columns].dtype=='O']
numerical_columns = [columns for columns in X.columns if X[columns].dtype!='O' and columns!='Blood Pressure']

In [20]:
print(ohe_columns)
print(numerical_columns)

['Sex', 'Diet']
['Age', 'Cholesterol', 'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week', 'Previous Heart Problems', 'Medication Use', 'Stress Level', 'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides', 'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'up', 'down']


In [21]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
one_hot_encoder = OneHotEncoder(drop='first')



preprocessor = ColumnTransformer(
    [
        ("StandardScaler", numeric_transformer, numerical_columns),
        ("OneHotEncoder", one_hot_encoder, ohe_columns)
    ],
    remainder='passthrough'
)

In [22]:
X = df.drop(columns=['Heart Attack Risk'])  # Keep it a DataFrame
y = df['Heart Attack Risk']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Now works fine with column-based transformers
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)


In [23]:
import pickle
import os

# Save preprocessor
with open('preprocessor.pkl', 'wb') as f:
    pickle.dump(preprocessor, f)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

In [25]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

In [26]:
scale_pos_weight = 5624 / 3139
weights = {
    0: 1.0,
    1: 1.79
}
models = {
    'XGBoost' : XGBClassifier(scale_pos_weight=scale_pos_weight, n_estimators=100),
    "Adaboost": AdaBoostClassifier(),
    "Random Forest": RandomForestClassifier(class_weight=weights, n_estimators=100),
    "Decision Tree": DecisionTreeClassifier(class_weight=weights),
    "Logistic": LogisticRegression(class_weight=weights, max_iter=1000),
}
trained_models = {}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    ## Training set performance
    model_train_accuracy = accuracy_score(y_train,y_train_pred)
    model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
    model_train_precision = precision_score(y_train,y_train_pred)
    model_train_recall = recall_score(y_train,y_train_pred)
    model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

    ## Testing set performance
    model_test_accuracy = accuracy_score(y_test,y_test_pred)
    model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')
    model_test_precision = precision_score(y_test,y_test_pred)
    model_test_recall = recall_score(y_test,y_test_pred)
    model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)


    print(list(models.keys())[i])

    print("Model Performance for Training set")
    print("- Accuracy: {:.4f}".format(model_train_accuracy))
    print("- F1 score: {:.4f}".format(model_train_f1))
    print("- Precision: {:.4f}".format(model_train_precision))
    print("- Recall: {:.4f}".format(model_train_recall))
    print("- ROC AUC Score: {:.4f}".format(model_train_rocauc_score))


    print('------------------------------------------------------------------')

    print("Model Performance for Test set")
    print("- Accuracy: {:.4f}".format(model_test_accuracy))
    print("- F1 score: {:.4f}".format(model_test_f1))
    print("- Precision: {:.4f}".format(model_test_precision))
    print("- Recall: {:.4f}".format(model_test_recall))
    print("- ROC AUC Score: {:.4f}".format(model_test_rocauc_score))

    trained_models[list(models.keys())[i]] = model

    print()

XGBoost
Model Performance for Training set
- Accuracy: 0.9948
- F1 score: 0.9948
- Precision: 0.9901
- Recall: 0.9955
- ROC AUC Score: 0.9949
------------------------------------------------------------------
Model Performance for Test set
- Accuracy: 0.5664
- F1 score: 0.5604
- Precision: 0.3795
- Recall: 0.3390
- ROC AUC Score: 0.5158

Adaboost
Model Performance for Training set
- Accuracy: 0.6420
- F1 score: 0.5032
- Precision: 0.8571
- Recall: 0.0027
- ROC AUC Score: 0.5012
------------------------------------------------------------------
Model Performance for Test set
- Accuracy: 0.6428
- F1 score: 0.5034
- Precision: 0.0000
- Recall: 0.0000
- ROC AUC Score: 0.4997

Random Forest
Model Performance for Training set
- Accuracy: 1.0000
- F1 score: 1.0000
- Precision: 1.0000
- Recall: 1.0000
- ROC AUC Score: 1.0000
------------------------------------------------------------------
Model Performance for Test set
- Accuracy: 0.6386
- F1 score: 0.5074
- Precision: 0.3000
- Recall: 0.009

In [27]:
# Save XGBClassifier
with open( 'xgboost_model.pkl', 'wb') as f:
    pickle.dump(trained_models['XGBoost'], f)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [ ]:
from sklearn.utils import class_weight
import numpy as np

In [ ]:
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weights_dict = dict(enumerate(class_weights))

In [ ]:
ann.fit(X_train, y_train, epochs=100, batch_size=32, class_weight=class_weights_dict)


Epoch 1/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6478 - loss: 0.6793
Epoch 2/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6241 - loss: 0.6719
Epoch 3/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6351 - loss: 0.6650
Epoch 4/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6222 - loss: 0.6723
Epoch 5/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6169 - loss: 0.6673
Epoch 6/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6255 - loss: 0.6618
Epoch 7/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6187 - loss: 0.6630
Epoch 8/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6193 - loss: 0.6589
Epoch 9/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5667 - loss: 0.6610
Epoch 10/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5696 - loss: 0.6585
Epoch 11/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5569 - loss: 0.6607
Epoch 12/100
192/192 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.4)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[1 0]
 [0 1]
 [1 1]
 ...
 [0 1]
 [1 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print(f'Accuracy score: {accuracy_score(y_test, y_pred)}')

[[ 339 1352]
 [ 174  764]]
Accuracy score: 0.4195511601369342


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=32, class_weight=class_weights_dict)


Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


192/192 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.4991 - loss: 0.6993
Epoch 2/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5052 - loss: 0.6944
Epoch 3/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4886 - loss: 0.6915
Epoch 4/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5027 - loss: 0.6954
Epoch 5/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4916 - loss: 0.6925
Epoch 6/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5320 - loss: 0.6878
Epoch 7/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4979 - loss: 0.6936
Epoch 8/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5430 - loss: 0.6881
Epoch 9/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5396 - loss: 0.6906
Epoch 10/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5283 - loss: 0.6898
Epoch 11/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5328 - loss: 0.6939
Epoch 12/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

83/83 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print(f'Accuracy score: {accuracy_score(y_test, y_pred)}')

[[ 638 1053]
 [ 371  567]]
Accuracy score: 0.4583491821985546
